### PR TITLE
Policy doesnt load certificate from preloaded json

### PR DESCRIPTION
**Pull request by AGaliuzov**
There are two issue regarding this:
- The `certificate` field is not mandatory and as the result in db schema
  should not be marked as `NOT NULL`
- The `certificate` is optional with `ModuleConfig` structure, so should
- be dereferenced before assign

Closes-Bug: [SDLWIN-234](https://adc.luxoft.com/jira/browse/SDLWIN-234)

### CODE REVIEW

**Comment by malirod** [comment]
Link to the issue in the description is invalid

**Comment by AGaliuzov** [comment]
fixed

**Comment by AGaliuzov** [comment]
@malirod, see 20f8781

**Comment by malirod** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
@anosach-luxoft, please review

**Comment by anosach-luxoft** [comment]
Reviewed

**Pull request merged**
