### PR TITLE
Make correct image verification

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Closes-bug: SDLWIN-235

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@anosach-luxoft, I already check this PR please let me know if you're going to make any changes here

**Comment by anosach-luxoft** [comment]
@AGaliuzov, yes I'm going. Please wait

**Comment by anosach-luxoft** [comment]
@malirod, see 230aedf

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
