### PR TITLE
Add termination by Ctrl-C for Qt

### PR DESCRIPTION
**Pull request by nk0leg**
Closes-Bug:[SDLWIN-334](https://adc.luxoft.com/jira/browse/SDLWIN-334)
Issue:[SDLWIN-295](https://adc.luxoft.com/jira/browse/SDLWIN-295)

### CODE REVIEW

**Comment by nk0leg** [comment]
@pestOO, @malirod, @anosach-luxoft please review

**Comment by malirod** [comment]
@nk0leg, how the crash (posix sigsegv) is handled on windows? I see only `ctrl+c` handling. We have some cleanup logic bind to this request. I don't like the idea to handle ctrl+c in win native way, and crash handling via posix signals emulation. We should use single approach at least on the same platform. If there is no native way to handle crash, maybe it worth to keep posix emulation?

**Comment by nk0leg** [comment]
@pestOO, @malirod< @anosach-luxoft  pull-request updated please look e54c0ee

**Comment by malirod** [comment]
Reviewed.

**Comment by anosach-luxoft** [comment]
@nk0leg @malirod I still have a doubts about this pull request changes. First of all we use WinAPI functions in Qt realization and it's not good. And the main thing: I don't know about any problems or defects with previous signals handling realization (please describe if you know) so I don't see the reason of such changes with possible regression.

**Comment by anosach-luxoft** [comment]
@pestOO please participate

**Comment by nk0leg** [comment]
https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx

**Comment by pestOO** [comment]
@nk0leg, approved events systems for Win and Native version.

**Pull request closed without merging**
