### PR TITLE
Build 32bit ssl as static library instead of dynamic

### PR DESCRIPTION
**Pull request by AGaliuzov**
Change build type to keep the same as for 64bit version

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@anosach-luxoft , @malirod please review

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by malirod** [comment]
@AGaliuzov, this PR conflicts with the prev one. I'm merging both PRs and have conflict. I propose to rebase this one on the prev one.

**Comment by AGaliuzov** [comment]
@malirod, Done

**Pull request merged**
