### PR TITLE
Update libusb with patch for hotplug feature

### PR DESCRIPTION
**Pull request by AGaliuzov**
The official release of libusb doesn't support hotplug
feature. This commit is a patch for hotplug.

Note: in order to make libusb workable on windows it is required to
install WinUsb driver

The patch has been taken [here](https://github.com/dickens/libusbx-hp/tree/windows-hotplug-3/libusb)

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@malirod , @anosach-luxoft , please review

**Comment by malirod** [comment]
@AGaliuzov, this is your own patch or you've took it from somewhere? If it came from the outer source I propose to post the source link too. I see a lot of changes in the thirdparty lib. I am not sure that it worth to check all these changes precisely.

**Comment by AGaliuzov** [comment]
Yes, sure it doesn't worth. Because I'm also do not understand all this changes.
I will update PR description with the link

**Comment by malirod** [comment]
I think update of the commit msg is better.

**Comment by anosach-luxoft** [comment]
@AGaliuzov, it doesn't work on my machine. After Android device plug (Nexus 4) I see
`libusb device arrived` in log, but right after that I see `libusb_claim_interface failed: LIBUSB_ERROR_NOT_SUPPORTED` and nothing happens. As I understand I've got a problem with WinUSB driver. @malirod, please try on your machine to make sure that I have local problems.

**Comment by anosach-luxoft** [comment]
Seems like I have a problem with Luxoft's USB ports using policy. According to them I have no access to USB ports.

**Pull request merged**
