### PR TITLE
Update clang-format config and reformat sources

### PR DESCRIPTION
**Pull request by malirod**
Disallow one-line if, while, function body.

### CODE REVIEW

**Comment by pestOO** [comment]
How we are going to merge this into the original repository?

**Comment by malirod** [comment]
@pestOO, there an opinion that if we will reformat both repos with the same config, then there will no huge difference and merge should be simple. In any case we should start applying reformatting.

**Comment by AGaliuzov** [comment]
@pestOO, @malirod the merge in any way will be quite hard.
Bu I agree with Rodion that we just need to perfrom the same stuff for current PASA repo

**Comment by pestOO** [comment]
@malirod, hope that it will helps. If not it will be a problem.

**Comment by malirod** [comment]
@pestOO, I hope too.

**Pull request merged**
