### PR TITLE
Add check if certificate has been set.

### PR DESCRIPTION
**Pull request by AGaliuzov**
The check if required in to avoid false-positive trigger for PTU

Fix: SDLWIN-339

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@LuxoftSDL/porting_team please review guys

**Comment by AGaliuzov** [comment]
@LuxoftSDL/porting_team, please review

**Comment by malirod** [comment]
@pestOO, @anosach-luxoft please review

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
#131 substitude this one

**Pull request closed without merging**
