### PR TITLE
Replace SharedPtr on a QSharedPointer

### PR DESCRIPTION
**Pull request by nk0leg**
see SDLWIN-133

### CODE REVIEW

**Comment by nk0leg** [comment]
@anosach-luxoft , @malirod  please review

**Comment by anosach-luxoft** [comment]
@nk0leg I agree with @AGaliuzov. Maybe try to use http://doc.qt.io/qt-4.8/qatomicint.html#details for reference counter in our custom shared pointer?

**Comment by malirod** [comment]
Here is my vision. Hand-made pointers are not the way to go. If there is the possibility to use mature and well known implementation, then it's better to use it.
Current PR introduce the adapter over the Qt shared pointer, which is quite widespread.
Usage of the qt atomic instead of hand-made atomic will not bring any beauty to the code, there will be still ifdefs (qt atomic doesn't fix our interface), but there will be potential issues of the hand-made impl.

**Comment by malirod** [comment]
@pestOO, please, participate. We need your opinion

**Comment by pestOO** [comment]
@malirod @nk0leg,
If `QSharedPointers` is not a part of customer requirements, it's not good idea to have two implementations.
`Atomic` looks the same.

**Comment by nk0leg** [comment]
Close.
see detail in #83

**Pull request closed without merging**
