### PR TITLE
Decrease log level to DEBUG

### LINKED ISSUE #80: Change log level to INFO
src/components/utils/src/rwlock_win.cc:117
(Try to acquire lock)

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Closes #80

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
@pestOO you are right. I'll remove it

**Comment by malirod** [comment]
@anosach-luxoft, what is the root of the problem with log level? Currently we have warn. So I assume that this is some kind of unexpected case. If the case is totally valid, then why we need info? Maybe debug is more suitable?

**Comment by anosach-luxoft** [comment]
@pestOO @malirod updated

**Comment by anosach-luxoft** [comment]
Hierarchy logging has been removed completely because of possible incorrect behavior in POSIX version. Actually without support of hierarchy logging from logger side this feature is useless

**Pull request merged**
