### PR TITLE
Add ability to build several openssl version

### PR DESCRIPTION
**Pull request by AGaliuzov**
Add ability to build several version (x86 and x64) at the same time
create separate environment variables for this

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by malirod** [comment]
@AGaliuzov, this doesn't work for me when I am building in the VS 2013

```
Error   1   error C1083: Cannot open include file: 'openssl/sha.h': No such file or directory (C:\workspace\sdl_core_winport\src\3rd_party-static\encryption\src\hashing.cc)    C:\workspace\sdl_core_winport\src\3rd_party-static\encryption\include\encryption\hashing.h  5   1   encryption
Error   4   error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory   C:\workspace\sdl_core_winport\src\components\config_profile\src\profile.cc  47  1   ConfigProfile
Error   10  error C1083: Cannot open include file: 'openssl/sha.h': No such file or directory (C:\workspace\sdl_core_winport\src\components\connection_handler\src\device.cc)   C:\workspace\sdl_core_winport\src\3rd_party-static\encryption\include\encryption\hashing.h  5   1   connectionHandler
Error   11  error C1083: Cannot open include file: 'openssl/bio.h': No such file or directory (C:\workspace\sdl_core_winport\src\components\security_manager\src\crypto_manager_impl.cc)    C:\workspace\sdl_core_winport\src\components\security_manager\include\security_manager\crypto_manager_impl.h    37  1   SecurityManager
Error   12  error C1083: Cannot open include file: 'openssl/bio.h': No such file or directory (C:\workspace\sdl_core_winport\src\components\security_manager\src\ssl_context_impl.cc)   C:\workspace\sdl_core_winport\src\components\security_manager\include\security_manager\crypto_manager_impl.h    37  1   SecurityManager
Error   13  error C1083: Cannot open include file: 'openssl/bio.h': No such file or directory (C:\workspace\sdl_core_winport\src\components\security_manager\src\security_manager_impl.cc)  C:\workspace\sdl_core_winport\src\components\security_manager\include\security_manager\crypto_manager_impl.h    37  1   SecurityManager

```

**Comment by AGaliuzov** [comment]
@malirod , is new environment variable has been set?

**Comment by malirod** [comment]
Which one? I've just rebuild.

**Comment by malirod** [comment]
In the PR description I see no new vars

**Comment by anosach-luxoft** [comment]
@AGaliuzov, I've got the same errors as @malirod when trying to run build in VS2013 after prop2013x64.cmd was successfuly completed. Please fix this.

**Comment by malirod** [comment]
@AGaliuzov, I prose to close this PR. Currently it doesn't  work and it creates issues for further builds. In any case you'll come back to not soon. Plus I have an idea to drop all env vars. So possibly this PR will be not relevant.
PR can be always reopened.

**Pull request closed without merging**
