### PR TITLE
Port tcp sockets usage to windows

### PR DESCRIPTION
**Pull request by malirod**
- use win event instead of pipe
- fix socket cleanup

@anosach-luxoft, @AGaliuzov, @pestOO please review

### CODE REVIEW

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by malirod** [comment]
@anosach-luxoft, see 2380a0c. All your comments should be fixed

**Comment by malirod** [comment]
I've added fixes for the tmp abs linux path handling.

**Comment by malirod** [comment]
I've added fix for the accept unblocking on shutdown.

**Comment by anosach-luxoft** [comment]
@malirod  :ok_hand:

**Comment by anosach-luxoft** [comment]
@malirod, I have a lot of errors in logs:
ERROR [10:41:22:517] [4600] [TransportManager] accept() failed. Error: 10035
when I try to register application via Wi-Fi with your changes

**Comment by malirod** [comment]
This f20e7d8 should fix the problem

**Comment by AGaliuzov** [comment]
reviewed

**Comment by malirod** [comment]
Please confirm that PR is ok. There is the conflict. I can rebase the branch.

**Comment by AGaliuzov** [comment]
I think you need to rebase first

**Comment by malirod** [comment]
ok

**Comment by malirod** [comment]
Rebased

**Pull request merged**
