### PR TITLE
Remove Profile singleton using from Policy library

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Comletely remove all calls by instance() from Policy.dll because of issue with singletons duplicating in dll in Windows. All parameters retrieved from Profile by instance() will be passed to policy library as constructor parameters.

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
@AGaliuzov, @pestOO, @malirod, please review.

**Comment by pestOO** [comment]
Is it cherry-pick from SDL?

**Comment by pestOO** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@pestOO, it's not a cherry-pick from SDL. Within singletons removing task another implementation will be provided.

**Comment by malirod** [comment]
@anosach-luxoft, who is responsible for manual merge & build? Propose to set "Assignee". "Visual review" is not always sufficient :)

**Comment by AGaliuzov** [comment]
reviwed

**Comment by malirod** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@malirod, @AGaliuzov, review has been updated

**Comment by malirod** [comment]
reviewed

**Comment by anosach-luxoft** [comment]
@malirod, see f4dcb0f and 0594cdc

**Comment by AGaliuzov** [comment]
reviewed

**Pull request merged**
