### PR TITLE
Pass logger to Policy.dll by reference

### LINKED ISSUE #87: Logging from policy dll doesn't work
In the sources logging is present. But it doesn't appear in the log file.

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Because of Windows dll libraries working specific SDL cannot receive logs from Policy.dll. To be able to log Policy.dll should use the same logger object as SDL.exe. Windows doesn't allow global instances sharing between exe and dll so we have to pass logger object from exe to dll by reference. This pull request provides wrapper for logger that passes to Policy.dll

Closes #87

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
@pestOO @malirod @nk0leg @AGaliuzov please review

**Comment by anosach-luxoft** [comment]
PR has been rebased

**Comment by pestOO** [comment]
Also, I was hope to see some kind of `DEBUG() << a << b << c`;
All what was doing in Porting was kinda Qt-way except this one =)

**Comment by malirod** [comment]
@pestOO, we don't port in Qt-style. Pimpl is not the qt idea. Some solutions (e.g. json) were dictating by Qt architecture. And actually i don't like it at all. I don't think that qt is well designed. 

Regarding logging style. Personally I don't like this qt-way of logging.

**Comment by pestOO** [comment]
@malirod,
I'm not insist - current implementation is equal to previous and normal.  
And Qt is сute =)

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
@anosach-luxoft , @malirod, @pestOO by the way guys I think we need to have a talk about adding doxygen in our code. @anosach-luxoft I don't see the comments for classes and methods.

**Comment by pestOO** [comment]
@AGaliuzov, right now we are updating commitment.md file - feel free to ask adding this as a mandatory part of PRs review.

**Comment by anosach-luxoft** [comment]
@malirod @pestOO @AGaliuzov PR has been updated. Also please see f7d4170 and 3ae4c33

**Pull request merged**
