### PR TITLE
Port SDL utils to Windows native platform

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Includes ports for such SDL classes as:
- MemoryBarrier
- Atomic
- Lock (pthread_mutex -> CRITICAL_SECTION)
- ConditionVariable (pthread_cond -> CONDITION_VARIABLE)
- RWLock (pthread_cond -> SRWLOCK)
- DateTime
- FileSystem
- Thread (pthread -> Windows native thread API)

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
@nk0leg, @AGaliuzov, @pestOO, please review

**Comment by nk0leg** [comment]
reviewed

**Comment by AGaliuzov** [comment]
@anosach-luxoft, please  consider that this branch is not mergable after merging of PR #6

**Comment by pestOO** [comment]
Reviewed

**Pull request merged**
