### PR TITLE
Fix 'QIODevice::open: File access not specified' for the Qt branch

### PR DESCRIPTION
**Pull request by nk0leg**
Fix: SDLWIN-360

### CODE REVIEW

**Comment by nk0leg** [comment]
@pestOO, @malirod, @anosach-luxoft please review

**Comment by pestOO** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Comment by nk0leg** [comment]
@malirod see 5ee4cbe

**Comment by nk0leg** [comment]
see [APPLINK-21524](https://adc.luxoft.com/jira/browse/APPLINK-21524)

**Comment by anosach-luxoft** [comment]
Reviewed

**Pull request merged**
