### PR TITLE
Format all sources with clang-format using google style as the base

### PR DESCRIPTION
**Pull request by malirod**
@pestOO, @AGaliuzov, @anosach-luxoft please review.

The formatting options are based on google config with small modification.
I've reformatted all sources, except `*3d_party*`. Seems there should be somewhere autogen code. If it so, let me know, it should not be formatted.

I assume the the last commit will be rebased during review.

After all sources will be reformatted, the next step will be to add precommit hook to catch issues with style before they will be published for review. This will allow to reduce style issues during future code reviews.

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
AFAIK we don't have autogen files in `src` directory. All our auto generated files are in `build/src/appMain` directory so you have not to exclude them. @AGaliuzov please correct me if I'm not right.
Also, I propose to add precommit hook within this pull request to avoid adding files with broken style.

**Comment by pestOO** [comment]
This beatifying will not simplify merge port back to SDL-core, wont't it?
May be plan the same beatifying in core?

**Comment by malirod** [comment]
@pestOO, my plan is to do things step by step. There is a small team on porting. So it should be not so  problematic to start using new features here. Then we can apply same things to the other repos.

**Comment by pestOO** [comment]
@malirod, We are on one side. Let's do it!

**Comment by pestOO** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
reviewed

**Comment by malirod** [comment]
@pestOO, see b0e6ce0. All your comments should be addressed.

**Comment by malirod** [comment]
@anosach-luxoft, I've updated this PR. I've added pre-commit hooks. Now this PR is based on the latest develop. Sources were reformatted once more time.
Hooks are not installed by default. To install pre-commit hooks run `python tools\infrastructure\install_hooks.py` in the project root.

**Pull request merged**
