### PR TITLE
Change URL characters encoding

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Change list of characters to be encoded according to
http://www.blooberry.com/indexdot/html/topics/urlencoding.htm

Closes-bug: SDLWIN-237

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@anosach-luxoft , are you going to change code according to the @malirod, suggestion?

**Comment by anosach-luxoft** [comment]
@AGaliuzov, @malirod, @pestOO, please review

**Comment by anosach-luxoft** [comment]
Comment with source has been added

**Comment by AGaliuzov** [comment]
reviewed

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
